# Generated by Django 2.2 on 2023-04-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(max_length=50)),
                ('port', models.IntegerField()),
                ('account', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('mail_from', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=200)),
                ('mail_body', models.CharField(max_length=1000)),
            ],
        ),
    ]
