# Generated by Django 2.2 on 2023-04-21 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Email',
            new_name='EmailSetting',
        ),
    ]
