# Generated by Django 2.2 on 2023-03-19 13:56

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20230319_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='建檔日期'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email1',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email1'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email2',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email2'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email3',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email3'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email4',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email4'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='啟用'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='mobile1',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[0-9+()-]+$', 'Enter a valid mobile number.', 'invalid')], verbose_name='手機1'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='mobile2',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator('^[0-9+()-]+$', 'Enter a valid mobile number.', 'invalid')], verbose_name='手機2'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(max_length=254, verbose_name='名稱'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='note',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='備註'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='send_email',
            field=models.BooleanField(default=False, verbose_name='Email通知'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='send_sms',
            field=models.BooleanField(default=False, verbose_name='簡訊通知'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tel1',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator('^[0-9+()-]+$', 'Enter a valid mobile number.', 'invalid')], verbose_name='連絡電話1'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tel2',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator('^[0-9+()-]+$', 'Enter a valid mobile number.', 'invalid')], verbose_name='連絡電話2'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Enter a valid username. This value may contain only letters, numbers and @/./+/-/_ characters.', 'invalid')], verbose_name='登入帳號'),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='type_name',
            field=models.CharField(max_length=50, verbose_name='類別'),
        ),
    ]
