# Generated by Django 2.2 on 2023-03-23 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20230322_1722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': (('view_cartype', 'car type view'), ('view_carcolor', 'car color view')), 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
