# Generated by Django 2.2 on 2023-03-24 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20230323_2033'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAuthority',
        ),
    ]
