# Generated by Django 2.2 on 2023-03-26 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_delete_userauthority'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostponeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_date', models.TextField(max_length=10, verbose_name='展延前到期日')),
                ('after_date', models.TextField(max_length=10, verbose_name='展延後到期日')),
                ('ip_addr', models.TextField(max_length=15, verbose_name='操作IP位置')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_postpone', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
