# Generated by Django 2.2 on 2023-03-26 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_postponerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='postponerecord',
            name='manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='postpone_manager_postpone', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postponerecord',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='postpone_user_postpone', to=settings.AUTH_USER_MODEL),
        ),
    ]
