# Generated by Django 2.2 on 2023-03-27 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20230326_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postponerecord',
            name='owner',
        ),
        migrations.AddField(
            model_name='postponerecord',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_postpone', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postponerecord',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='manager_postpone', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LoginRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_addr', models.TextField(max_length=15, verbose_name='登入IP')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_login', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
