# Generated by Django 2.2 on 2023-03-28 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_searchrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchrecord',
            old_name='car_no',
            new_name='words',
        ),
    ]
