# Generated by Django 2.2 on 2023-04-10 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_uploadrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadRecord',
        ),
    ]
