# Generated by Django 2.2 on 2023-03-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=50)),
                ('CARNO_2', models.CharField(max_length=50)),
                ('NO_2', models.CharField(max_length=50)),
                ('DATE_2', models.CharField(max_length=50)),
                ('TIME_2', models.CharField(max_length=50)),
                ('ADDR_2', models.CharField(max_length=50)),
                ('GPS_2A', models.CharField(max_length=50)),
                ('GPS_2B', models.CharField(max_length=50)),
                ('MARK_2', models.CharField(max_length=50)),
                ('SALES_2', models.CharField(max_length=50)),
                ('BINGO_2', models.CharField(max_length=50)),
                ('UPDATE_2', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('CARNO_2', 'DATE_2', 'TIME_2')},
            },
        ),
    ]
