# Generated by Django 2.2 on 2023-03-17 01:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gps',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gps',
            name='create_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='gps_create_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
