# Generated by Django 2.2 on 2023-04-09 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gps', '0002_gpsowner'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPS_PHOTO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=50)),
                ('FILE', models.CharField(max_length=50)),
                ('CARNO', models.CharField(max_length=50)),
                ('DATE', models.CharField(max_length=50)),
                ('TIME', models.CharField(max_length=50)),
                ('GPS_2A', models.CharField(max_length=50)),
                ('GPS_2B', models.CharField(max_length=50)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='gps_photo_create_at', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='GPSOwner',
        ),
    ]
