# Generated by Django 2.2 on 2023-04-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0003_auto_20230409_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gps_photo',
            name='FILE',
            field=models.CharField(max_length=100),
        ),
    ]
