# Generated by Django 2.2 on 2023-04-10 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0005_auto_20230409_1654'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gps',
            unique_together=set(),
        ),
    ]
