# Generated by Django 2.2 on 2023-03-19 13:35

from django.db import migrations, models
import django.utils.timezone
import jobs.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=50)),
                ('file_type', models.CharField(blank=True, max_length=50)),
                ('file', models.FileField(null=True, upload_to=jobs.models.user_directory_path)),
                ('count', models.IntegerField()),
                ('success', models.IntegerField(default=0)),
                ('start_time', models.CharField(blank=True, max_length=50)),
                ('end_time', models.CharField(blank=True, max_length=50)),
                ('exe_time', models.IntegerField(null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_en', models.CharField(max_length=50)),
                ('status_cn', models.CharField(max_length=50)),
                ('status_desc', models.TextField()),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
