# Generated by Django 2.2 on 2023-03-19 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobstatus',
            name='create_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='job_status_create_at', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobstatus',
            name='update_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='job_status_update_at', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='filejob',
            name='create_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='job_create_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='filejob',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='job_status', to='jobs.JobStatus'),
        ),
    ]
