# Generated by Django 2.2 on 2023-02-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_filejob_batch_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='filejob',
            name='exe_time',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filejob',
            name='start_time',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
