# Generated by Django 2.2 on 2023-03-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20230227_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='filejob',
            name='end_time',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
