# Generated by Django 2.2 on 2023-03-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_filejob_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filejob',
            name='success',
            field=models.IntegerField(default=0),
        ),
    ]
