# Generated by Django 2.2 on 2023-03-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20230314_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filejob',
            name='exe_time',
            field=models.IntegerField(null=True),
        ),
    ]
