# Generated by Django 2.2 on 2023-03-09 06:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='batch_no',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
