# Generated by Django 2.2 on 2023-03-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_auto_20230319_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='CARNO2',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
