# Generated by Django 2.2 on 2023-04-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_car_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_photo',
            name='FILE',
            field=models.CharField(max_length=100),
        ),
    ]
